### ISSUE TITLE
一键删除平台监控脚本，会删除系统模块aegis128*.ko

### ISSUE THREAD

**Issue by saymyname77** [spiritLHLS/one-click-installation-script#4]
cd / 后，find . -iname "*aegis*" 会搜索到如下系统模块并删除，请确认是否合理...
./usr/lib/modules/6.5.0-0.deb12.1-amd64/kernel/arch/x86/crypto/aegis128-aesni.ko
./usr/lib/modules/6.5.0-0.deb12.1-amd64/kernel/crypto/aegis128.ko

**Comment by saymyname77** [comment]
@spiritLHLS @SuperYuIuo @pb222xd

**Comment by spiritLHLS** [comment]
我问一下做linux系统开发的朋友，稍后回复

**Comment by spiritLHLS** [comment]
![图片](https://github.com/spiritLHLS/one-click-installation-script/assets/103393591/08eb7b74-5b55-4392-b9e4-057b37a1b61b)
![图片](https://github.com/spiritLHLS/one-click-installation-script/assets/103393591/0815af8f-6412-4056-88e8-454ac535199d)
https://www.kernelconfig.io/config_crypto_aegis128_aesni_sse2
确实是原本就该有的，项目本身有问题

**Comment by spiritLHLS** [comment]
https://github.com/spiritLHLS/one-click-installation-script/commit/64e0203ecc056ef7f765da3f17a23cd2d051d793

已去除错误代码

**Comment by spiritLHLS** [comment]
![图片](https://github.com/spiritLHLS/one-click-installation-script/assets/103393591/414e518a-e09e-4def-b4a6-0f809ef9dd42)
![图片](https://github.com/spiritLHLS/one-click-installation-script/assets/103393591/d1f622a1-59e6-40e4-94a9-4f331fa6d7f1)
```
lsmod | grep aegis128-aesni
```
内核中有但是不一定启用了 朋友说这两个模块比较小众 不是默认编译安装的选项 初始环境中本身也没加载
